### ISSUE TITLE
OnGoing - Each Player incorrect conversion

### ISSUE THREAD

**Issue by LionariusPy** [hmmhmmhm/dva-engine#4]
![image](https://user-images.githubusercontent.com/45388086/63857297-19727480-c9ac-11e9-843a-37e361332e20.png)

OnGoing - Each Player after conversion becomes

![image](https://user-images.githubusercontent.com/45388086/63857361-3e66e780-c9ac-11e9-8eca-5102b200d40d.png)

instead of

![image](https://user-images.githubusercontent.com/45388086/63857402-4cb50380-c9ac-11e9-86ec-d2f475c029a3.png)

**Comment by hmmhmmhm** [comment]
Thank you for letting me know!
