### ISSUE TITLE
Value.globalVariable expected 0 arguments

### ISSUE THREAD

**Issue by LionariusPy** [hmmhmmhm/dva-engine#5]
![image](https://user-images.githubusercontent.com/45388086/63864851-39f4fb80-c9b9-11e9-86aa-f5d0bb96f968.png)

![image](https://user-images.githubusercontent.com/45388086/63864963-6872d680-c9b9-11e9-899d-ae0ff939af89.png)

Global Variable must have Type.Variable. argument like in Player Variable

![image](https://user-images.githubusercontent.com/45388086/63864947-5f820500-c9b9-11e9-8bc7-6da3ab4c85d4.png)

**Comment by LionariusPy** [comment]
It should look like this 
![image](https://user-images.githubusercontent.com/45388086/63865107-b1c32600-c9b9-11e9-9cf1-bc2c1b6cdd92.png)

**Comment by hmmhmmhm** [comment]
There was a wrong space typo in the code... Thx!
The function is now works well.

![12](https://user-images.githubusercontent.com/38493722/63867134-501dae80-c9ef-11e9-9efb-c50308ef697f.png)
