### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by LionariusPy** [hmmhmmhm/dva-engine#7]
![image](https://user-images.githubusercontent.com/45388086/63872634-b8a46580-c9c6-11e9-8d94-0987de6d836e.png)

![image](https://user-images.githubusercontent.com/45388086/63872653-bfcb7380-c9c6-11e9-912d-dd0f2cb444e1.png)

Says Type.IGlobal. but needs Type.Variable.
Says Type.Variable. but needs Type.VariableOperation.

Same for other Modify Variable Actions

**Comment by hmmhmmhm** [comment]
Patch's applied! Thank you!
